# Generated by Django 4.1.4 on 2023-01-14 10:29

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("icon_url", models.URLField(blank=True)),
                ("description", models.TextField()),
                (
                    "parent_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children_categories",
                        to="products.productcategory",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="product",
            name="variantion_product_ids",
        ),
        migrations.AddField(
            model_name="product",
            name="variation_product_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(blank=True, null=True),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.DeleteModel(
            name="ProductCatergory",
        ),
    ]
